### ISSUE TITLE
Dark side toggle

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#1]
As a **site user** I can **join the dark side** so that **I can be a sith lord**

### Acceptance Criteria
- [x] 1. There's a toggle for sith or jedi
- [x] 2. Clicking the toggle changes alignment
- [x] 3. Filters the display of lightsabers for sith / jedi wielders

### Tasks
- [x] 1. Create a toggle (checkbox) for light/dark side
- [x] 2. Create functions to toggle the display
- [x] 3. Filter the lightsabers based on light/dark alignment
- [x] 4. Create a cool design that makes it clear what the toggle does

**Comment by JesseRoss001** [comment]
I believe this is done except style changes
