### ISSUE TITLE
Accessible UI/UX

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#10]
As a **user with disabilities** I can **use the site in a way that works for me** so that **I can enjoy the site without struggle**

### Acceptance Criteria
- [x] 1. Contrast is high enough for individuals with blurred eyesight and color-blindness
- [x] 2. Screen readers can convey everything important and omit everything irrelevant to individuals with severe vision impairments and dyslexia
- [x] 3. Animations and transitions are contained in a media query so that individuals with epilepsy, motion sickness, and vestibular balance issues can safely open the site

### Tasks
- [x] 1. Use high-contrast colors and test the contrast value with tools such as lighthouse
- [x] 2. Use tags such as aria-label, aria-hidden, and alt-text to guide screen readers. 
- [x] 3. Test the site using a screen reader.
- [x] 4. Place a `(prefers-reduced-motion: no-preference)` media query around animations
- [x] 5. Test the site with motion preferences set to reduced motion
