### ISSUE TITLE
Improved Ease of Use

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#11]
As a **site user** I can **interact with the page intuitively** so that **I have a nice experience with the site**

### Acceptance Criteria
- [x] 1. Sections and elements are clearly defined with visual cues
- [x] 2. Texts and other content are defined to follow an intuitive hierarchy of importance
- [x] 3. Interactive elements such as links and buttons stand out and have a large clickable area

### Tasks
- [x] 1. Double-check the use of semantic html tags
- [x] 2. Fine-tune the spacing and styling of elements
- [x] 3. Add hover/focus effects, cursor changes, and more wherever necessary
