### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#12]
As a **site user** I can **view the page in a format appropriate for my screen** so that **I can use the site as intended on any device**

### Acceptance Criteria
- [x] 1. All pages have a responsive design from 280px to 1400+
- [x] 2. Elements do not overflow on small screens
- [x] 3. Images are responsive and don't bog down the page load on mobile internet
- [x] 4. Buttons and other clickable items are large enough to tap on a phone
- [x] 5. Sections/containers do not stretch out into thin strips on large monitors
- [x] 6. Mobile users can turn the phone to either orientation without breaking the page

### Tasks
- [x] 1. Use responsive bootstrap classes and custom CSS to ensure responsive design
- [x] 2. Use responsive img or picture tags and implement lazy loading
- [x] 3. Check the size and padding on buttons
- [x] 4. Set a max-width for elements that would need it and didn't get it from bootstrap
- [x] 5. Test the site on phones in portrait and landscape mode, as well as large/extra-wide monitors
