### ISSUE TITLE
Scrolling Text Hero Star Wars Style 

### ISSUE THREAD

**Issue by JesseRoss001** [EmilionR/jedi-blades-hackathon#17]
As a site user I can see from the hero text what the site is about  so that I understand the content of the website 

### Acceptance Criteria
- [x] 1. The text is high quality and fit for the intended  purpose 
- [x] 2. The text matches the colour scheme, typography + padding and margin 
- [x] 3. The text scrolls responsively on all different screen sizes 

### Tasks
- [x] 1. Generate text possibly different lengths depending on screen size 
- [x] 2. Style the text with CSS 
- [x] 3. Bootstrap for responsiveness container 
- [x] 4. Set different view heights for different screen sizes 
- [x] 5. Ensure the star wars scroll effect works and looks good on all devices
