### ISSUE TITLE
Content Policy 

### ISSUE THREAD

**Issue by JesseRoss001** [EmilionR/jedi-blades-hackathon#18]
As a **user** I can **trust jedi-blades ** so that **I can understand the the rights of their imagery and intentions **

### Acceptance Criteria
- [x] 1. Full legal statement 
- [x] 2. Accessible from the footer in a modal 
- [x] 3. Reviewed by 2 team members 
- [x] 4. Information is reflected in documentation 

### Tasks
- [x] 1. Copy wookiepedia and replace with our team name and website name
- [x] 2. Add the required footer text/link 
- [x] 3. Ensure read me is up to date with copyright information and fair use policy

**Comment by JesseRoss001** [comment]
Hi @emilyrosenberg and @EmilionR  would you mind reviewing this for me please
