### ISSUE TITLE
List of Lightsabers

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#3]
As a **site user** I can **see a list of all lightsabers** so that **I can browse and find the one I want to see**

### Acceptance Criteria
- [x] 1. Users can view a page that displays all lightsabers
- [x] 2. All lightsabers appear in an organized list
- [x] 3. Lightsaber entries can be clicked

### Tasks
- [x] 1. Create a page for the lightsaber list
- [x] 2. Load lightsabers using template logic
- [x] 3. Wire up links for each lightsaber

**Comment by JesseRoss001** [comment]
This issue should be updated as all lightsabers will acquire an image and this should be reflected in the model . Another consideration that has not been listed is the visual display for the lightsabers and where to find high quality imagery for each .
