### ISSUE TITLE
Lightsaber Details

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#4]
As a **site user** I can **view a dedicated page for a specific lightsaber** so that **I can learn more about it**

### Acceptance Criteria
- [x] 1. Users can click a lightsaber from the list page to get to the detail page
- [x] 2. The detail page displays an image of the lightsaber
- [x] 3. The detail page has information about the lightsaber

### Tasks
- [x] 1. Create a lightsaber details page
- [x] 2. Load the lightsaber details from the correct lightsaber model

**Comment by JesseRoss001** [comment]
Again, the modal should be updated to contain an image field. In order to complete this
