### ISSUE TITLE
Character List

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#5]
As a **site user** I can **view a list of characters** so that **I can browse and find any character**

### Acceptance Criteria
- [ ] 1. Users can view a page that lists the characters
- [ ] 2. Characters appear in an organized list view
- [ ] 3. Character entries can be clicked and interacted with

### Tasks
- [x] 1. Create a "Characters" page
- [ ] 2. Load character entries from Django models
- [ ] 3. Wire up links for character entries
