### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#57]
As a **site user** I can **hear sound effects** so that **I can get immersed in the Star Wars vibe**

### Acceptance Criteria
- [x] 1. User interactions play sound effects
- [x] 2. All sound effects are relevant to the Star Wars theme

### Tasks
- [x] 1. Gather sound effects
- [x] 2. Connect sound effects to events
