### ISSUE TITLE
Character Details Page

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#6]
As a **site user** I can **view a character's details page** so that **I can learn more about the character**

### Acceptance Criteria
- [ ] 1. Users can click a character from the list to open the details page
- [ ] 2. The details page contains information about the character
- [ ] 3. The details page features an image of the character
- [ ] 4. The details page has a link to the character's lightsaber

### Tasks
- [ ] 1. Create character details page
- [ ] 2. Load information about the character from its Django model
- [ ] 3. Set up links to lightsaber pages
