### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#7]
As a **site user** I can **view a page about the team** so that **I  can learn about the developers behind the project**

### Acceptance Criteria
- [x] 1. Users can view an "About us" page that lists the team members
- [x] 2. The site can be accessed from the main navigation menu

### Tasks
- [x] 1. Create an team page
- [x] 2. Add an entry for each team member
- [x] 3. Add a navigation link for the team page

**Comment by JesseRoss001** [comment]
Team page created
