### ISSUE TITLE
Team members

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#8]
As a **site user** I can **see the team members** so that **I can learn more about the team**

### Acceptance Criteria
- [x] 1. There's an image for each team member
- [x] 2. There's a line describing the role(s) of each team member
- [x] 3. There's a link to each team member's profile on GitHub and/or LinkedIn

### Tasks
- [x] 1. Add a card (div or article with 'card' class) for each member
- [x] 2. Add a responsive image to each member card
- [x] 3. Add an h3 with the person's name
- [x] 4. Add a subtitle (h4 or strong) with the person's role(s)
- [x] `optional` _Add a short text blurb describing the team member_
