### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/jedi-blades-hackathon#9]
As a **site user** I can **easily navigate the site** so that **I can find any page or section without issues**

### Acceptance Criteria
- [x] 1. There's a navigation menu present across the site
- [x] 2. All relevant navigation links are present in the navigation menu

### Tasks
- [x] 1. Create a navigation menu
- [x] 2. Assemble navigation links

**Comment by JesseRoss001** [comment]
The team must decide if the characters will be on an entirely new page.
